BATCH_SIZE: 64
TRAIN_SIZE: 16384
TEST_SIZE: 4096
GRAD_CLIP: 5.0
LENGTHS: "random"
NUM_SEGMENTS: 3
LEARNING_RATE: 0.0001
WEIGHT_DECAY: 0.0001
NUM_EPOCHS: 10000
ANALYSIS_INTERVAL: 1
SEED: 1337
NOISE_INJ: 0.1
LAMBDA_FWD: 1.0
LAMBDA_INV: 1.0
LAMBDA_FWD_BND: 1.0
LAMBDA_INV_BND: 0.1
LAMBDA_IND: 1.0
INN_WIDTH: 512
INN_DEPTH: 8